// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ5aAeN4SVywf96FzTVzC1ck0Qys0Qw0M',
    appId: '1:368924981202:web:3590615a4a31ab401dfa0b',
    messagingSenderId: '368924981202',
    projectId: 'event-planner-3c308',
    authDomain: 'event-planner-3c308.firebaseapp.com',
    storageBucket: 'event-planner-3c308.firebasestorage.app',
    measurementId: 'G-1LZ2T3EQ0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXG41rHN2VZBFKkAgspWZE48ULZaYoNGE',
    appId: '1:368924981202:android:3a4c141a428a3d131dfa0b',
    messagingSenderId: '368924981202',
    projectId: 'event-planner-3c308',
    storageBucket: 'event-planner-3c308.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcWAzVcKIjJbGRKhLgczm0j6Uh1Ky87M',
    appId: '1:368924981202:ios:abd540afbf5b9c9b1dfa0b',
    messagingSenderId: '368924981202',
    projectId: 'event-planner-3c308',
    storageBucket: 'event-planner-3c308.firebasestorage.app',
    iosBundleId: 'com.apptest.eventplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClcWAzVcKIjJbGRKhLgczm0j6Uh1Ky87M',
    appId: '1:368924981202:ios:eb6d51eeba5f0d631dfa0b',
    messagingSenderId: '368924981202',
    projectId: 'event-planner-3c308',
    storageBucket: 'event-planner-3c308.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ5aAeN4SVywf96FzTVzC1ck0Qys0Qw0M',
    appId: '1:368924981202:web:383f802d21ae3af91dfa0b',
    messagingSenderId: '368924981202',
    projectId: 'event-planner-3c308',
    authDomain: 'event-planner-3c308.firebaseapp.com',
    storageBucket: 'event-planner-3c308.firebasestorage.app',
    measurementId: 'G-X9T2ST957Y',
  );
}
